import assert from "node:assert/strict";
import test from "node:test";
import { randomUUID } from "node:crypto";
import { createPersonnelFixture, personnelFixtureIds as ids } from "./fixture";
import type { PersonnelDetail, PersonnelList } from "./model";

test("workspace personnel preserves identities, periods and leave grants and enforces offboarding", async () => {
  const db = await createPersonnelFixture();
  const rpc = async <T>(sql: string, args: unknown[]) => (await db.query<{ data: T }>(sql, args)).rows[0].data;
  const query = (id: string | null = null, actor = ids.root) => rpc<PersonnelDetail & PersonnelList>("select public.personnel_query($1,$2,$3) data", [ids.workspace, actor, id]);
  const save = (body: object, actor = ids.root) => rpc<string>("select public.personnel_save($1,$2,$3::jsonb) data", [ids.workspace, actor, JSON.stringify(body)]);
  try {
    await db.exec("set role authenticated");
    await assert.rejects(query(), /permission denied/);
    await assert.rejects(db.query("select * from personnel_private.employees"), /permission denied/);
    await db.exec("reset role; set role service_role");
    for (const actor of [ids.manager, ids.staff, ids.outsider]) await assert.rejects(query(null, actor), /최고관리자/);
    const initial = await query();
    const staff = initial.items.find(e => e.user_id === ids.staff)!;
    const body = { id: staff.id, expected_version: staff.version, action: "update", user_id: ids.staff, email: staff.email, name: "직원 이름", address: "주소", phone: "010-0000-0000", memo: "메모", employment_start_date: "2020-01-01", contract_end_date: null, annual_salary: 50000000, reason: "수정", effective_date: "2026-01-01" };
    await db.query("insert into public.hr_annual_leave_grants(workspace_id,user_id,grant_year,granted_days,employment_start_date,granted_by) values($1,$2,2026,12,'2020-01-01',$3)", [ids.workspace, ids.staff, ids.root]);
    await save({ ...body, resident_number: "0001013000000", bank_name: "검증은행", bank_account: "001-002-0003" });
    let detail = await query(staff.id);
    assert.equal(detail.employee.name, body.name);
    assert.equal(detail.employee.has_resident_number, true);
    assert.ok(!JSON.stringify(detail).includes("0001013000000"));
    assert.equal(detail.employee.bank_name, "검증은행");
    assert.equal(detail.employee.bank_account, "001-002-0003");
    const revealed = await rpc<string>("select public.personnel_reveal($1,$2,$3) data", [ids.workspace, ids.root, staff.id]);
    assert.equal(revealed, "0001013000000");
    await assert.rejects(save(body), /다른 변경/);
    const current = () => ({ ...body, expected_version: detail.employee.version });
    const task = await rpc<{ id: string }>("select public.create_work_task_with_event($1,'업무','','2026-01-01',$2) data", [ids.workspace, ids.staff]);
    await assert.rejects(save({ ...current(), action: "resign" }), /미완료/);
    await db.query("update public.work_tasks set status='done' where id=$1", [task.id]);
    await save({ ...current(), action: "resign" });
    detail = await query(staff.id);
    assert.equal(detail.employee.status, "resigned");
    assert.equal(detail.periods[0].end_date, "2026-01-01");
    assert.equal(await rpc<boolean>("select public.personnel_access($1,$2) data", [ids.workspace, ids.staff]), false);
    await assert.rejects(db.query("update public.work_tasks set status='open' where id=$1", [task.id]), /퇴직한 직원/);
    await assert.rejects(db.query("insert into public.hr_leave_requests(workspace_id,user_id,leave_date,unit) values($1,$2,'2026-01-02','full')", [ids.workspace, ids.staff]), /퇴직한 직원/);
    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [ids.staff]);
    await db.exec("reset role; set role authenticated");
    assert.equal((await db.query("select * from public.work_tasks")).rows.length, 0);
    assert.equal((await db.query("select * from public.hr_annual_leave_grants")).rows.length, 0);
    await db.exec("reset role; set role service_role");
    await assert.rejects(save({ ...current(), action: "rehire", employment_start_date: "2026-01-01" }), /재입사일/);
    await save({ ...current(), action: "rehire", employment_start_date: "2026-01-02", effective_date: "2026-01-02" });
    detail = await query(staff.id);
    assert.equal(detail.employee.status, "employed");
    assert.equal(detail.periods.length, 2);
    assert.equal(detail.periods[1].start_date, "2020-01-01");
    assert.equal(await rpc<boolean>("select public.personnel_access($1,$2) data", [ids.workspace, ids.staff]), true);
    assert.equal(Number((await db.query<{ granted_days: string }>("select granted_days from public.hr_annual_leave_grants where user_id=$1", [ids.staff])).rows[0].granted_days), 12);
    await save({ ...current(), action: "dismiss", employment_start_date: "2026-01-02", effective_date: "2026-01-03" });
    detail = await query(staff.id);
    assert.equal(detail.employee.status, "dismissed");
    assert.equal(detail.employee.address, "주소");
    assert.equal(detail.events.length, 5);
    assert.equal(detail.employee.bank_account, "001-002-0003");
    const newBody = { ...body, id: undefined, expected_version: undefined, action: "hire", user_id: null, email: "hire@example.test", effective_date: "2020-01-01" };
    const newId = await save(newBody);
    assert.equal((await query(newId)).employee.user_id, null);
    await assert.rejects(save(newBody), /duplicate key/);
    await assert.rejects(save({ ...newBody, email: "x@example.test", user_id: ids.outsider }), /워크스페이스/);
    await assert.rejects(query(randomUUID()), /직원을 찾을/);
    const root = initial.items.find(e => e.user_id === ids.root)!;
    await assert.rejects(save({ ...body, id: root.id, user_id: ids.root, expected_version: root.version, action: "resign" }), /본인을/);
    await db.exec("reset role");
    assert.equal((await db.query<{ resident_number: string }>("select resident_number from personnel_private.employees where id=$1", [staff.id])).rows[0].resident_number, "0001013000000");
    await assert.rejects(db.query("delete from auth.users where id=$1", [ids.staff]), /foreign key/);
  } finally { await db.close(); }
});
