"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { BASE_LABELS, STATUS_LABELS, formatTime, type DaySummary, type Employee, type Policy, type PolicyConfig } from "@/lib/hr/types";
import { ErrorNotice, Field, Pager, Panel, selectClass, useHr, useHrMutation, useHrQuery } from "./shared";
import { RecordsPage } from "./records";
import { LeavesPage } from "./leaves";
import { TasksPage } from "./tasks";

function EmployeeForm({ employee, saved }: { employee?: Employee; saved: () => void }) {
  const { today } = useHr(); const mutation = useHrMutation();
  return <form className="grid gap-4 sm:grid-cols-2" onSubmit={async event => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const fields = { name: String(data.get("name")), department: String(data.get("department")), role: String(data.get("role")), employment_start_date: String(data.get("start")) }; try { await mutation.mutate(employee ? "employee.update" : "invitation.reserve", employee ? { ...fields, id: employee.id, expected_version: employee.version, active: data.get("active") === "on", employment_end_date: String(data.get("end") || "") || null, reason: String(data.get("reason")) } : { ...fields, email: String(data.get("email")) }); if (!employee) form.reset(); saved(); } catch {} }}>
    <Field label="이름"><Input name="name" required maxLength={100} defaultValue={employee?.name} /></Field><Field label="부서"><Input name="department" maxLength={100} defaultValue={employee?.department} /></Field>
    {!employee && <Field label="초대 이메일"><Input type="email" name="email" required /></Field>}<Field label="역할"><select name="role" defaultValue={employee?.role ?? "employee"} className={selectClass}><option value="employee">직원</option><option value="admin">관리자</option></select></Field><Field label="입사일"><Input type="date" name="start" required defaultValue={employee?.employment_start_date ?? today} /></Field>
    {employee && <><Field label="퇴사일 (비활성화 시)"><Input type="date" name="end" defaultValue={employee.employment_end_date ?? ""} /></Field><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" name="active" defaultChecked={employee.active} />활성 직원</label><div className="sm:col-span-2"><Field label="변경 사유"><Textarea name="reason" required maxLength={2000} /></Field></div></>}
    <div className="space-y-3 sm:col-span-2"><ErrorNotice error={mutation.error} /><Button disabled={mutation.busy}>{mutation.busy ? "처리 중…" : employee ? "직원 정보 저장" : "초대 메일 보내기"}</Button>{!employee && <p className="text-xs text-muted-foreground">버튼을 누르면 인증용 초대 메일을 한 번 발송합니다.</p>}</div>
  </form>;
}
function InvitationActions({ invitation, saved }: { invitation: { id: string; status: string }; saved: () => void }) {
  const mutation = useHrMutation();
  if (!["failed", "sending", "pending"].includes(invitation.status)) return null;
  const action = invitation.status === "sending" ? "invitation.inspect" : "invitation.retry";
  return <div className="mt-2"><ErrorNotice error={mutation.error} /><Button size="sm" variant="outline" disabled={mutation.busy} onClick={async () => { try { await mutation.mutate(action, { id: invitation.id }); saved(); } catch {} }}>{action === "invitation.retry" ? "초대 메일 재시도" : "계정 연결 결과 확인"}</Button></div>;
}
function EmployeesPage() {
  const [page, setPage] = useState(0); const query = useHrQuery<{ items: Employee[]; total: number; invitations_total: number; invitations: { id: string; name: string; email: string; status: string }[] }>("employees", { page });
  return <><Panel title="직원 초대"><EmployeeForm saved={query.reload} /></Panel><Panel title="직원 관리"><ErrorNotice error={query.error} retry={query.reload} /><div className="space-y-3">{query.data?.items.map(employee => <details key={`${employee.id}-${employee.version}`} className="rounded-lg border p-4"><summary className="cursor-pointer text-sm font-medium">{employee.name} · {employee.department || "부서 미지정"} · {employee.role === "admin" ? "관리자" : "직원"} · {employee.active ? "활성" : "비활성"}</summary><p className="my-3 text-xs text-muted-foreground">{employee.email}</p><EmployeeForm employee={employee} saved={query.reload} /></details>)}</div><Pager page={page} total={Math.max(query.data?.total ?? 0, query.data?.invitations_total ?? 0)} onPage={setPage} /></Panel><Panel title="초대 기록"><ul className="space-y-3 text-sm">{query.data?.invitations.map(invitation => <li key={invitation.id}>{invitation.name} · {invitation.email} · {({ pending: "전송 대기", sending: "전송 결과 확인 필요", sent: "초대 완료", failed: "전송 실패" } as Record<string,string>)[invitation.status]}<InvitationActions invitation={invitation} saved={query.reload} /></li>)}</ul></Panel></>;
}
const timeValue = (minutes: number) => `${String(Math.floor(minutes / 60)).padStart(2,"0")}:${String(minutes % 60).padStart(2,"0")}`;
const minutesValue = (value: string) => { const [h,m] = value.split(":").map(Number); return h * 60 + m; };
type Impact = { leave_id: string; employee_name: string; before_units: number; after_units: number; before: unknown[]; after: unknown[] };
function PolicyEditor({ policy, saved }: { policy: Policy; saved: () => void }) {
  const { today } = useHr(); const mutation = useHrMutation(); const [days, setDays] = useState(policy.config.weekdays); const [preview, setPreview] = useState<{ body: Record<string, unknown>; impact: Impact[] }>(); const [message, setMessage] = useState("");
  const nextDay = new Date(`${today}T00:00:00Z`); nextDay.setUTCDate(nextDay.getUTCDate() + 1);
  return <form className="space-y-4" onChange={() => setPreview(undefined)} onSubmit={async event => {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    const config: PolicyConfig = { weekdays: days, start: minutesValue(String(form.get("start"))), end: minutesValue(String(form.get("end"))), split: minutesValue(String(form.get("split"))), grace: Number(form.get("grace")),
      breaks: String(form.get("breaks")).split("\n").filter(line => line.trim()).map(line => line.split("-").map(value => minutesValue(value.trim()))),
      holidays: String(form.get("holidays")).split("\n").filter(line => line.trim()).map(line => { const [date,...name] = line.split(","); return { date: date.trim(), name: name.join(",").trim() }; }) };
    const body = { effective_from: String(form.get("effective")), expected_version: policy.version, config };
    try { const result = await mutation.mutate<{ impact: Impact[] }>("policy.preview", body); setPreview({ body, impact: result.impact }); } catch {}
  }}>
    <p className="text-sm text-muted-foreground">새 정책은 적용 시작일부터 사용합니다. 과거 출퇴근 기준은 보존됩니다.</p><Field label="적용 시작일"><Input name="effective" type="date" required min={nextDay.toISOString().slice(0,10)} defaultValue={nextDay.toISOString().slice(0,10)} /></Field>
    <fieldset><legend className="mb-2 text-sm font-medium">근무 요일</legend><div className="flex flex-wrap gap-3">{["월", "화", "수", "목", "금", "토", "일"].map((label,index) => <label className="flex min-h-11 items-center gap-2 text-sm" key={label}><input type="checkbox" checked={days.includes(index + 1)} onChange={event => setDays(event.target.checked ? [...days,index + 1] : days.filter(day => day !== index + 1))} />{label}</label>)}</div></fieldset>
    <div className="grid gap-4 sm:grid-cols-4"><Field label="근무 시작"><Input name="start" type="time" required defaultValue={timeValue(policy.config.start)} /></Field><Field label="근무 종료"><Input name="end" type="time" required defaultValue={timeValue(policy.config.end)} /></Field><Field label="오전/오후 반차 경계"><Input name="split" type="time" required defaultValue={timeValue(policy.config.split)} /></Field><Field label="지각 여유 (분)"><Input name="grace" type="number" min={0} max={120} required defaultValue={policy.config.grace} /></Field></div>
    <Field label="휴게시간 (한 줄에 시작-종료, 예: 12:00-13:00)"><Textarea name="breaks" defaultValue={policy.config.breaks.map(([start,end]) => `${timeValue(start)}-${timeValue(end)}`).join("\n")} /></Field>
    <Field label="휴무일 (한 줄에 날짜,이름)"><Textarea name="holidays" rows={5} placeholder="2026-10-09,한글날" defaultValue={policy.config.holidays.map(day => `${day.date},${day.name}`).join("\n")} /></Field>
    <ErrorNotice error={mutation.error} />{message && <p role="status">{message}</p>}<Button variant="outline" disabled={mutation.busy}>변경 영향 미리보기</Button>
    {preview && <div className="space-y-3 rounded-lg border border-amber-200 bg-amber-50 p-4"><p className="font-medium">영향받는 휴가 {preview.impact.length}건</p><ul className="space-y-2 text-sm">{preview.impact.map(item => <li key={item.leave_id}>{item.employee_name} · {item.before_units}일 → {item.after_units}일<details><summary>변경 구간 확인</summary><p className="break-all">{JSON.stringify(item.before)} → {JSON.stringify(item.after)}</p></details></li>)}</ul><Button type="button" disabled={mutation.busy} onClick={async () => { try { await mutation.mutate("policy.save", { ...preview.body, confirm_impact: preview.impact }); setPreview(undefined); setMessage("새 근무정책을 저장했습니다."); saved(); } catch {} }}>영향을 확인하고 정책 저장</Button></div>}
  </form>;
}
function SettingsPage() {
  const policies = useHrQuery<{ items: Policy[] }>("policies"); const outbox = useHrQuery<{ items: { id: string; event_type: string; attempts: number; last_error: string; next_retry_at: string }[] }>("outbox");
  return <><Panel title="근무정책·휴무일"><ErrorNotice error={policies.error} retry={policies.reload} />{policies.data?.items[0] && <PolicyEditor key={policies.data.items[0].version} policy={policies.data.items[0]} saved={policies.reload} />}<ul className="mt-6 space-y-2 text-sm text-muted-foreground">{policies.data?.items.map(policy => <li key={policy.id}>버전 {policy.version} · {policy.effective_from}부터 적용</li>)}</ul></Panel><Panel title="알림 처리 대기" actions={<Button variant="outline" onClick={outbox.reload}>새로고침</Button>}><ErrorNotice error={outbox.error} retry={outbox.reload} /><ul className="space-y-2 text-sm">{outbox.data?.items.map(event => <li key={event.id}>{event.event_type} · 시도 {event.attempts}회 · 다음 처리 {formatTime(event.next_retry_at)}{event.last_error && ` · 오류 ${event.last_error}`}</li>)}</ul>{!outbox.data?.items.length && <p className="text-sm text-muted-foreground">처리 대기 중인 알림이 없습니다.</p>}</Panel></>;
}
function AdminDashboard({ selectEmployee }: { selectEmployee: (id: string, date: string) => void }) {
  const { today } = useHr(); const [date, setDate] = useState(today); const [q, setQ] = useState(""); const [department, setDepartment] = useState(""); const [base, setBase] = useState(""); const [needs, setNeeds] = useState(false); const [missing, setMissing] = useState(false); const [page, setPage] = useState(0);
  const data = useHrQuery<{ items: DaySummary[]; counts: Record<string,number> | null; people_total: number; total: number; now: string }>("admin", { date, q, department, base, needs_attention: String(needs), review_missing: String(missing), page }, true);
  return <><div className="grid gap-3 sm:grid-cols-4"><Field label="기준 날짜"><Input type="date" value={date} onChange={e => { setDate(e.target.value); setPage(0); }} /></Field><Field label="직원 이름"><Input value={q} onChange={e => { setQ(e.target.value); setPage(0); }} /></Field><Field label="부서"><Input value={department} onChange={e => { setDepartment(e.target.value); setPage(0); }} /></Field><Field label="근태 상태"><select className={selectClass} value={base} onChange={e => { setBase(e.target.value); setPage(0); }}><option value="">전체</option>{Object.entries(BASE_LABELS).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></Field></div>
    <div className="flex flex-wrap items-center justify-between gap-3 text-sm"><div className="flex flex-wrap gap-4"><label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={needs} onChange={e => { setNeeds(e.target.checked); setPage(0); }} />확인 필요</label><label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={missing} onChange={e => { setMissing(e.target.checked); setPage(0); }} />업무정리 미완료</label></div><div className="flex flex-wrap items-center gap-2"><span className="text-xs text-muted-foreground">마지막 갱신 {formatTime(data.refreshed)} · 활성 화면에서 30초마다 갱신</span><Button variant="outline" onClick={data.reload}>새로고침</Button></div></div><ErrorNotice error={data.error} retry={data.reload} />
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-7">{Object.entries(BASE_LABELS).map(([value,label]) => <div className="rounded-xl border bg-white p-4" key={value}><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{data.data?.counts?.[value] ?? 0}</p></div>)}</div>
    <Panel title={`직원별 현황 · 대상 ${data.data?.people_total ?? 0}명`}><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead><tr className="border-b"><th className="py-3">직원</th><th>상태</th><th>출근 / 퇴근</th><th>참고 근무시간</th><th>확인 사항</th><th>현재 담당 업무 누계</th><th>오늘 활동</th></tr></thead><tbody>{data.data?.items.map(day => <tr key={day.employee_id} className="border-b"><td className="py-4"><Button variant="link" className="p-0" onClick={() => selectEmployee(day.employee_id, date)}>{day.name}</Button><p className="text-xs text-muted-foreground">{day.department}</p></td><td>{BASE_LABELS[day.base]}</td><td>{formatTime(day.attendance?.check_in_at)}<br />{formatTime(day.attendance?.check_out_at)}</td><td>{day.reference_minutes == null ? "—" : `${day.reference_minutes}분`}</td><td className="max-w-40 text-xs">{[day.late && "지각",day.long_open && "장시간 미종료",day.prior_open && "전일 퇴근 미체크",day.leave_conflict && "휴가·근태 겹침",day.pending_correction && "정정 접수",day.review_missing && "정리 미완료",day.review_version && `정리 ${day.review_version}차 제출`,day.review_late && "사후 작성",...day.leave_segments.map(segment => segment === "am" ? "오전반차" : "오후반차")].filter(Boolean).join(" · ") || "—"}</td><td className="text-xs">{Object.entries(STATUS_LABELS).map(([status,label]) => <p key={status}>{label} {day.task_counts?.[status] ?? 0}</p>)}</td><td><div className="mb-2 text-xs">{Object.entries(STATUS_LABELS).map(([status,label]) => <p key={status}>{label} {day.today_task_counts?.[status] ?? 0}</p>)}</div>{day.today_activity ?? 0}회 활동<br /><span className="text-xs">이관 {day.today_transfers ?? 0}건</span></td></tr>)}</tbody></table></div><Pager page={page} total={data.data?.total ?? 0} onPage={setPage} /></Panel>
  </>;
}
export function AdminPage() {
  const { me } = useHr(); const [tab, setTab] = useState("attendance"); const [person, setPerson] = useState<string>(); const [recordDate, setRecordDate] = useState<string>();
  if (me.role !== "admin") return <ErrorNotice error="관리자만 이용할 수 있습니다." />;
  return <><h1 className="text-2xl font-semibold">관리자</h1><nav aria-label="관리자 메뉴" className="flex gap-2 overflow-x-auto pb-2">{[["attendance","근태"],["records","직원 상세"],["tasks","업무"],["leaves","휴가"],["employees","직원"],["settings","설정"]].map(([value,label]) => <Button className="shrink-0" key={value} variant={tab === value ? "default" : "outline"} onClick={() => setTab(value)}>{label}</Button>)}</nav>
    {tab === "attendance" && <AdminDashboard selectEmployee={(id, date) => { setPerson(id); setRecordDate(date); setTab("records"); }} />}{tab === "records" && <RecordsPage key={person} admin initialEmployeeId={person} initialDate={recordDate} />}{tab === "tasks" && <TasksPage admin />}{tab === "leaves" && <LeavesPage admin />}{tab === "employees" && <EmployeesPage />}{tab === "settings" && <SettingsPage />}
  </>;
}
