"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { BASE_LABELS, STATUS_LABELS, formatTime, monthRange, type Correction, type DaySummary, type Review, type Task, type Employee } from "@/lib/hr/types";
import { ErrorNotice, Field, Pager, Panel, PersonSelect, useHr, useHrList, useHrMutation, useHrQuery } from "./shared";
import { DayCard, ReviewComposer } from "./today";

export function CorrectionForm({ day, employeeId, admin, saved }: { day: DaySummary; employeeId: string; admin: boolean; saved: () => void }) {
  const mutation = useHrMutation(); const localValue = (value: string | undefined | null) => value ? new Date(new Date(value).getTime() + 9 * 3600000).toISOString().slice(0,16) : "";
  return <form className="space-y-4" onSubmit={async event => { event.preventDefault(); const data = new FormData(event.currentTarget); const checkout = String(data.get("out")); const fields = { work_date: day.date, check_in_at: new Date(`${data.get("in")}:00+09:00`).toISOString(), check_out_at: checkout ? new Date(`${checkout}:00+09:00`).toISOString() : null, reason: String(data.get("reason")) }; try { await mutation.mutate(admin ? "correction.direct" : "correction.request", admin ? { ...fields, employee_id: employeeId, expected_version: day.attendance?.version ?? 0 } : fields); saved(); } catch {} }}>
    <p className="text-sm">{day.date} · 모든 시각은 서울 기준입니다. 퇴근 시각을 비우면 열린 출근 기록으로 처리합니다.</p><Field label="희망 출근 시각"><Input name="in" type="datetime-local" required defaultValue={localValue(day.attendance?.check_in_at) || `${day.date}T09:00`} /></Field><Field label="희망 퇴근 시각"><Input name="out" type="datetime-local" defaultValue={localValue(day.attendance?.check_out_at)} /></Field><Field label="정정 사유"><Textarea name="reason" required maxLength={2000} /></Field><ErrorNotice error={mutation.error} /><Button disabled={mutation.busy}>{admin ? "사유를 남기고 정정 반영" : "정정 요청"}</Button>
  </form>;
}
function ResolveCorrection({ correction, saved }: { correction: Correction; saved: () => void }) {
  const mutation = useHrMutation(); const [decision, setDecision] = useState("applied");
  return <form className="space-y-3 rounded-lg border p-3" onSubmit={async event => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await mutation.mutate("correction.resolve", { id: correction.id, decision, reason: String(form.get("reason")) }); saved(); } catch {} }}>
    <p className="text-sm">희망 시각 {formatTime(correction.requested_in)} ~ {formatTime(correction.requested_out)}</p><div className="flex gap-4 text-sm"><label><input type="radio" checked={decision === "applied"} onChange={() => setDecision("applied")} /> 반영</label><label><input type="radio" checked={decision === "rejected"} onChange={() => setDecision("rejected")} /> 반려</label></div><Field label="관리자 검토 사유"><Textarea name="reason" required maxLength={2000} /></Field><ErrorNotice error={mutation.error} /><Button disabled={mutation.busy}>정정 요청 처리</Button>
  </form>;
}
type Records = { days: DaySummary[]; total: number; reviews: Review[]; reviews_total: number; corrections: Correction[]; corrections_total: number; audit_total: number; audit: { id: string; reason: string; before_data: Record<string, unknown>; after_data: Record<string, unknown>; created_at: string }[] };
function PastReview({ date, version, done }: { date: string; version: number; done: () => void }) {
  const tasks = useHrList<Task>("tasks", { scope: "all", status: "all" });
  return <><ErrorNotice error={tasks.error} retry={tasks.reload} />{tasks.items && <ReviewComposer workDate={date} tasks={tasks.items} version={version} reload={tasks.reload} done={done} past />}</>;
}
export function RecordsPage({ admin = false, initialEmployeeId, initialDate }: { admin?: boolean; initialEmployeeId?: string; initialDate?: string }) {
  const { today, me } = useHr(); const [person, setPerson] = useState(initialEmployeeId ?? me.id); const [range, setRange] = useState(monthRange((initialDate ?? today).slice(0,7))); const [page, setPage] = useState(0); const [selected, setSelected] = useState<DaySummary>(); const [mode, setMode] = useState<"detail" | "correct" | "review">("detail");
  const data = useHrQuery<Records>("records", { ...range, employee_id: person, page }); const close = () => { setSelected(undefined); data.reload(); };
  const people = useHrList<Employee>(admin ? "employees" : "directory");
  return <><h1 className="text-2xl font-semibold">{admin ? "직원별 기록" : "내 기록"}</h1><div className="flex flex-wrap gap-4"><Field label="시작일"><Input type="date" value={range.from} onChange={e => { setRange({ ...range, from: e.target.value }); setPage(0); }} /></Field><Field label="종료일"><Input type="date" value={range.to} onChange={e => { setRange({ ...range, to: e.target.value }); setPage(0); }} /></Field>{admin && <Field label="직원"><PersonSelect value={person} options={people.items} onChange={value => { setPerson(value); setPage(0); }} /></Field>}</div><ErrorNotice error={data.error} retry={data.reload} />
    <Panel title="날짜별 근태"><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr className="border-b text-muted-foreground"><th className="py-3">날짜</th><th>상태</th><th>출근</th><th>퇴근</th><th>참고 근무시간</th><th>업무정리</th><th>상세</th></tr></thead><tbody>{data.data?.days.map(day => <tr key={day.date} className="border-b"><td className="py-4">{day.date}</td><td>{BASE_LABELS[day.base]}</td><td>{formatTime(day.attendance?.check_in_at)}</td><td>{formatTime(day.attendance?.check_out_at)}</td><td>{day.reference_minutes == null ? "—" : `${day.reference_minutes}분`}</td><td>{day.review_version ? `${day.review_version}차 제출` : "미정리"}</td><td><Button size="sm" variant="outline" onClick={() => { setSelected(day); setMode("detail"); }}>상세</Button></td></tr>)}</tbody></table></div><Pager page={page} total={Math.max(data.data?.total ?? 0, data.data?.reviews_total ?? 0, data.data?.corrections_total ?? 0, data.data?.audit_total ?? 0)} onPage={setPage} /></Panel>
    <Panel title="정정 요청"><div className="space-y-4">{data.data?.corrections.map(correction => <article className="rounded-lg bg-slate-50 p-4" key={correction.id}><p className="font-medium">{correction.work_date} · {({ pending: "접수", applied: "반영", rejected: "반려" } as Record<string, string>)[correction.status]}</p><p className="my-2 whitespace-pre-wrap text-sm">{correction.reason}</p>{correction.review_reason && <p className="text-sm">검토 사유: {correction.review_reason}</p>}{admin && correction.status === "pending" && <ResolveCorrection correction={correction} saved={data.reload} />}</article>)}{!data.data?.corrections.length && <p className="text-sm text-muted-foreground">이 기간의 정정 요청이 없습니다. 날짜 상세에서 정정을 요청할 수 있습니다.</p>}</div></Panel>
    <Panel title="제출한 업무정리"><div className="space-y-4">{data.data?.reviews.map(review => <details key={review.id} className="rounded-lg border p-4"><summary className="cursor-pointer font-medium">{review.work_date} · {review.revision}차 제출 {review.late && "· 사후 작성"}</summary><p className="mt-3 text-xs text-muted-foreground">제출 시각 {formatTime(review.submitted_at)}</p><p className="my-3 whitespace-pre-wrap text-sm">{review.note || "메모 없음"}</p><ul className="space-y-2 text-sm">{review.items.map(item => <li key={item.id}>TASK-{item.task_number} · {item.title} · {item.assignee_name} · {STATUS_LABELS[item.status]} · 버전 {item.version}{item.work_note && <p>{item.work_note}</p>}</li>)}</ul>{!review.items.length && <p className="text-sm">등록된 업무 없음</p>}</details>)}{!data.data?.reviews.length && <p className="text-sm text-muted-foreground">아직 제출한 업무정리가 없습니다.</p>}</div></Panel>
    {data.data?.audit.length ? <Panel title="근태 정정 이력"><ul className="space-y-3 text-sm">{data.data.audit.map(audit => <li key={audit.id} className="rounded-lg border p-3"><p>{formatTime(audit.created_at)} · {audit.reason}</p><p className="mt-2">출근: {formatTime(audit.before_data?.check_in_at as string)} → {formatTime(audit.after_data?.check_in_at as string)}</p><p>퇴근: {formatTime(audit.before_data?.check_out_at as string)} → {formatTime(audit.after_data?.check_out_at as string)}</p></li>)}</ul></Panel> : null}
    <Dialog open={Boolean(selected)} onOpenChange={open => { if (!open) setSelected(undefined); }}><DialogContent className="max-h-[92dvh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>{selected?.date} {mode === "correct" ? "근태 정정" : mode === "review" ? "업무정리" : "기록 상세"}</DialogTitle><DialogDescription>저장된 기록과 제출 시점의 정리를 확인합니다.</DialogDescription></DialogHeader>{selected && (mode === "correct" ? <CorrectionForm day={selected} employeeId={person} admin={admin} saved={close} /> : mode === "review" ? <PastReview date={selected.date} version={selected.review_version} done={close} /> : <><DayCard day={selected} /><div className="mt-5 flex flex-wrap gap-2"><Button onClick={() => setMode("correct")}>근태 정정{admin ? "" : " 요청"}</Button>{person === me.id && selected.date <= today && <Button variant="outline" onClick={() => setMode("review")}>업무정리 작성·재제출</Button>}</div></>)}</DialogContent></Dialog>
  </>;
}
