import { escapePrintHtml as escape } from "./print";
import { comparisonLabels, type ComparisonEntry, type ComparisonGroup } from "./roster-comparison";

const won = (value: number) => `${value.toLocaleString("ko-KR")}원`;
function entries(rows: ComparisonEntry[]) {
  if (!rows.length) return '<p class="missing">해당 내역 없음</p>';
  return `<details><summary>원본 ${rows.length}건</summary>${rows.map(row => `<article><strong>${escape(row.name || "이름 없음")}</strong><p>ID: ${escape(row.paymentId || "없음")}</p><p>${escape([row.phone, row.email].filter(Boolean).join(" · "))}</p><p>${escape(row.description)}</p><p class="source">${escape(row.source)}</p><p>결제 ${won(row.payment)} · 환불 ${won(row.refund)} · 잔액 ${won(row.net)}</p></article>`).join("")}</details>`;
}
export function comparisonWindowHtml(courseName: string, instructor: string, groups: ComparisonGroup[]) {
  const counts = Object.fromEntries(Object.keys(comparisonLabels).map(status => [status, groups.filter(row => row.status === status).length]));
  const rowHtml = groups.map(group => {
    const side = (rows: ComparisonEntry[], total: ComparisonGroup["orderTotal"], other: ComparisonGroup["orderTotal"]) => `<td>${rows.length ? `<dl>${([['결제', 'payment'], ['환불', 'refund'], ['잔액', 'net']] as const).map(([label, key]) => `<div class="${total[key] !== other[key] ? 'changed' : ''}"><dt>${label}</dt><dd>${won(total[key])}</dd></div>`).join("")}</dl>` : ''}${entries(rows)}</td>`;
    return `<tr data-status="${group.status}" class="${group.status}"><th scope="row"><strong>${escape(group.name)}</strong><p class="source">ID: ${escape(group.paymentId || "없음 · 수동 확인")}</p><span class="status">${comparisonLabels[group.status]}</span><span class="delta">잔액 차이<br>${won(group.orderTotal.net - group.settlementTotal.net)}</span></th>${side(group.orders, group.orderTotal, group.settlementTotal)}${side(group.settlements, group.settlementTotal, group.orderTotal)}</tr>`;
  }).join("");
  return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(courseName)} · 명단 비교</title><style>
*{box-sizing:border-box}body{margin:0;color:#18181b;background:#fff;font:14px/1.6 Arial,"Malgun Gothic",sans-serif;letter-spacing:0}header,main{padding:24px;max-width:1600px;margin:auto}header{border-bottom:1px solid #d4d4d8}h1{font-size:24px;margin:0 0 8px}p{margin:4px 0;overflow-wrap:anywhere}.meta,.source{color:#52525b;font-size:12px}.legend,.tools{display:flex;gap:12px;flex-wrap:wrap;margin-top:16px}.legend span{padding:4px 10px;border-left:5px solid}.orders-only{--accent:#1d4ed8;--tint:#eff6ff}.settlement-only{--accent:#be123c;--tint:#fff1f2}.different{--accent:#a16207;--tint:#fefce8}.review{--accent:#7e22ce;--tint:#faf5ff}.matched{--accent:#047857;--tint:#f0fdf4}.legend span,tr th{background:var(--tint);border-color:var(--accent)}input,select{font:inherit;padding:8px 10px;border:1px solid #a1a1aa;border-radius:4px;max-width:100%}input[type=search]{width:300px}input[type=checkbox]{accent-color:#1d4ed8}.tools label{display:flex;align-items:center;gap:6px}.scroll{overflow-x:auto;border:1px solid #d4d4d8}table{border-collapse:collapse;width:100%;min-width:740px;table-layout:fixed}th,td{padding:16px;vertical-align:top;border-bottom:1px solid #d4d4d8;text-align:left;overflow-wrap:anywhere}thead th{background:#f4f4f5}thead th:first-child{width:20%}tbody th{border-left:5px solid var(--accent)}td{border-left:1px solid #e4e4e7}tr:not(.matched) td{background:var(--tint)}.status{display:block;color:var(--accent);font-weight:bold;margin-top:6px}.delta{display:block;font-size:12px;font-weight:normal;margin-top:12px}dl{margin:0 0 12px}dl div{display:flex;justify-content:space-between;gap:8px;padding:4px}dd{margin:0;font-weight:600;font-variant-numeric:tabular-nums}.changed{background:#fef08a;color:#713f12}.missing{font-weight:600;color:#71717a}summary{cursor:pointer;font-weight:600}article{border-top:1px solid #d4d4d8;padding:10px 0}.empty{padding:24px;text-align:center;color:#52525b}[hidden]{display:none!important}@media(max-width:640px){header,main{padding:16px}h1{font-size:20px}.tools{flex-direction:column;align-items:stretch}}@media print{.tools{display:none}.scroll{overflow:visible}table{min-width:0}*{print-color-adjust:exact}}
</style></head><body><header><h1>주문·정산 명단 비교</h1><p>${escape(courseName)} · ${escape(instructor)}</p><p class="meta">전체 주문내역 ↔ 해당 강사 누적 정산의 토스·무통장 거래 · 부가서비스 제외</p><p class="meta">주문 결제ID ↔ 토스 E열 주문번호 기준. ID 없는 거래는 확인 필요. 가상계좌 입금대기·전액환불 주문은 제외. 잔액 차이 = 주문 − 정산.</p><div class="legend">${Object.entries(comparisonLabels).map(([key, label]) => `<span class="${key}">${label} ${counts[key]}명</span>`).join("")}</div><div class="tools"><input type="search" id="search" aria-label="ID·이름·연락처 검색" placeholder="ID·이름·연락처 검색"><select id="status" aria-label="비교 상태"><option value="all">전체 상태</option>${Object.entries(comparisonLabels).map(([key,label])=>`<option value="${key}">${label}</option>`).join('')}</select><label><input type="checkbox" id="differences">차이만 보기</label><label><input type="checkbox" id="expand">원본 전체 펼치기</label></div></header><main><p id="count" role="status"></p><div class="scroll"><table><thead><tr><th>결제ID / 비교 결과</th><th>주문내역</th><th>강사 누적 정산내역</th></tr></thead><tbody>${rowHtml}</tbody></table><p id="empty" class="empty" hidden>해당하는 내역이 없습니다.</p></div></main><script>
const rows=Array.from(document.querySelectorAll('tbody tr'));const search=document.getElementById('search'),status=document.getElementById('status'),differences=document.getElementById('differences');
function filter(){const q=search.value.normalize('NFKC').replace(/\\s/g,'').toLowerCase();let count=0;for(const row of rows){row.hidden=!(row.textContent.normalize('NFKC').replace(/\\s/g,'').toLowerCase().includes(q)&&(status.value==='all'||row.dataset.status===status.value)&&(!differences.checked||row.dataset.status!=='matched'));if(!row.hidden)count++;}document.getElementById('count').textContent=count+' / '+rows.length+'개 ID 그룹';document.getElementById('empty').hidden=count!==0;}search.addEventListener('input',filter);status.addEventListener('change',filter);differences.addEventListener('change',filter);document.getElementById('expand').addEventListener('change',event=>document.querySelectorAll('details').forEach(detail=>detail.open=event.target.checked));filter();
</script></body></html>`;
}
